### ISSUE TITLE
sqlalchemy dependency failing

### ISSUE THREAD

**Issue by Sorcecoder** [app-generator/flask-datta-able#1]
Hi I wasnt able to get the app to run unfortunately.
It has to do something with  sqlalchemy dependencys. Here my error log
```
PS C:\Users\PavelH\Documents\GitHub\hegler-tech-dashboard> flask run
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask_sqlalchemy\__init__.py:851: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  warnings.warn(
c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask_sqlalchemy\__init__.py:872: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  warnings.warn(FSADeprecationWarning(
Traceback (most recent call last):
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PavelH\AppData\Local\Programs\Python\Python39\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 305, in __init__
    self._load_unlocked()
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 257, in locate_app
    return find_best_app(script_info, module)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 117, in call_factory
    return app_factory(script_info)
  File "C:\Users\PavelH\Documents\GitHub\hegler-tech-dashboard\app\__init__.py", line 39, in create_app
    register_blueprints(app)
  File "C:\Users\PavelH\Documents\GitHub\hegler-tech-dashboard\app\__init__.py", line 22, in register_blueprints
    module = import_module('app.{}.routes'.format(module_name))
  File "c:\users\pavelh\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\PavelH\Documents\GitHub\hegler-tech-dashboard\app\base\routes.py", line 17, in <module>
    from app.base.models import User
  File "C:\Users\PavelH\Documents\GitHub\hegler-tech-dashboard\app\base\models.py", line 7, in <module>
    from sqlalchemy import Binary, Column, Integer, String
ImportError: cannot import name 'Binary' from 'sqlalchemy' (c:\users\pavelh\appdata\local\programs\python\python39\lib\site-packages\sqlalchemy\__init__.py)
```

**Comment by Sorcecoder** [comment]
label:bug

**Comment by app-generator** [comment]
The product is not using the latest version of `sqlalchemy`.  Current versions are:
- flask_sqlalchemy = 2.4.4
- sqlalchemy = 1.3.23
